version: '3.4'

services:
  scalable-web-app:
    image: ${DOCKER_REGISTRY-}scalablewebapp
    build:
      context: .
      dockerfile: scalable-web-app/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
    - scalable-web-api
  scalable-web-api:
    image: ${DOCKER_REGISTRY-}scalablewebapi
    build:
      context: .
      dockerfile: scalable-web-api/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"
